### PR TITLE
SPLAT-1630: Bump API version to get new VSphereMultiVCenters featuregate.

### PR DESCRIPTION
**Pull request by vr4manta**
[SPLAT-1630](https://issues.redhat.com//browse/SPLAT-1630)

### Changes
- Bump API to get new VSphereMultiVCenters featuregate
- Removed code that moved to openshift/api

### Notes
When bumping the openshift/api, the featuregate / featureset logic has changed quite a bit resulting in refactoring that would take a while; however, the code needing to be refactored has been moved into openshift/api from this project.  There is a flag (--skip-rendering) that has been on in bootkube.sh for a while now to skip the logic.  I believe we  were just waiting on hypershift to update their install to use the new featuregate in openshift/api so we can remove this.  For now, I've removed it to see if things are ready to be removed.

### CODE REVIEW

**Comment by vr4manta** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn

**Comment by vr4manta** [comment]
/payload-job periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn

**Review by JoelSpeed — COMMENTED** [review]
Changes look good, any reason not to move out of draft?

**Comment by vr4manta** [comment]
> Changes look good, any reason not to move out of draft?

Just wanted a review from you about the tests being good.  I'll undraft.  Thanks!

**Pull request merged**
