### PR TITLE
Bump openshift/api

### PR DESCRIPTION
**Pull request by umohnani8**
Update vendor to pull in API changes made to the
images.config.openshift.io and proxy CRD.

Signed-off-by: Urvashi Mohnani <umohnani@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
@soltysh @mfojtik @deads2k PTAL

**Comment by umohnani8** [comment]
@soltysh @mfojtik  AWS jobs have been down for a while now, is there a way to get this in without the 2 AWS jobs? We need this in before the feature freeze deadline.

**Comment by mfojtik** [comment]
@umohnani8 lets give it couple more retests, some failures were due to VPC quota, but the recent failures looks real, worrisome.

**Comment by mfojtik** [comment]
@umohnani8 

```
E1202 12:35:18.366479       1 task.go:81] error running apply for customresourcedefinition "images.config.openshift.io" (40 of 656): CustomResourceDefinition.apiextensions.k8s.io "images.config.openshift.io" is invalid: spec.validation.openAPIV3Schema.properties[spec].properties[registrySources].properties[containerRuntimeSearchRegistries].uniqueItems: Forbidden: uniqueItems cannot be set to true since the runtime complexity becomes quadratic
```

you have bug in your CRD :-)

/hold

**Comment by ingvagabund** [comment]
@umohnani8 can you wait until https://github.com/openshift/api/pull/806 gets merged and sync again?

**Comment by ingvagabund** [comment]
Are you syncing the changes from openshift/api master branch?

**Comment by umohnani8** [comment]
Not form the master, I picked the commit of the fix that went in. But I can sync from master if needed

**Comment by damemi** [comment]
@umohnani8 if you could sync from master that would be great (we have a change we also want to land into CCO for feature freeze), but if not we can open a follow up PR after this one merges

**Comment by umohnani8** [comment]
@damemi done, vendored in openshift/api master :)

**Comment by umohnani8** [comment]
Bumped it up to include https://github.com/openshift/api/pull/806 as well, should be up to date with openshift/api master now

**Review by soltysh — APPROVED** [review]
/lgtm
/hold cancel

**Comment by umohnani8** [comment]
I think the tests should pass now, looks like the client-go bump was causing a failure. The client-go bump was not needed, so reverted that.

**Comment by umohnani8** [comment]
I am seeing this in the apiserver logs
```
I1204 01:03:03.623622       1 reflector.go:207] Starting reflector *v1.SecurityContextConstraints (10m0s) from k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156
E1204 01:03:03.638994       1 reflector.go:127] k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1.SecurityContextConstraints: failed to list *v1.SecurityContextConstraints: the server could not find the requested resource (get securitycontextconstraints.security.openshift.io)
```
but `k8s.io/client-go` is at 0.19.0 https://github.com/openshift/cluster-config-operator/pull/168/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R20, so not sure where it is getting the `v0.19.2` from.

**Comment by ingvagabund** [comment]
From bootstrapping's `log-bundle-20201204122241/bootstrap/containers/cluster-policy-controller-f2819772d57ff998de8379296a74838a1c4bf696c8f7d62a5b3d0d5009b069e4.log`
```
unable to retrieve the complete list of server APIs: apps.openshift.io/v1: the server is currently unable to handle the request, authorization.openshift.io/v1: the server is currently unable to handle the request, build.openshift.io/v1: the server is currently unable to handle the request, image.openshift.io/v1: the server is currently unable to handle the request, project.openshift.io/v1: the server is currently unable to handle the request, quota.openshift.io/v1: the server is currently unable to handle the request, route.openshift.io/v1: the server is currently unable to handle the request, security.openshift.io/v1: the server is currently unable to handle the request, template.openshift.io/v1: the server is currently unable to handle the request
```

**Comment by ingvagabund** [comment]
From log-bundle-20201204122241/bootstrap/pods/932c7b4371c5.log:
```
[#1] failed to create some manifests:
"0000_03_security-openshift_01_scc.crd.yaml": failed to create customresourcedefinitions.v1.apiextensions.k8s.io/securitycontextconstraints.security.openshift.io -n : CustomResourceDefinition.apiextensions.k8s.io "securitycontextconstraints.security.openshift.io" is invalid: [spec.additionalPrinterColumns[0].JSONPath: Required value, spec.additionalPrinterColumns[1].JSONPath: Required value, spec.additionalPrinterColumns[2].JSONPath: Required value, spec.additionalPrinterColumns[3].JSONPath: Required value, spec.additionalPrinterColumns[4].JSONPath: Required value, spec.additionalPrinterColumns[5].JSONPath: Required value, spec.additionalPrinterColumns[6].JSONPath: Required value, spec.additionalPrinterColumns[7].JSONPath: Required value, spec.additionalPrinterColumns[8].JSONPath: Required value]
Failed to create "0000_03_security-openshift_01_scc.crd.yaml" customresourcedefinitions.v1.apiextensions.k8s.io/securitycontextconstraints.security.openshift.io -n : CustomResourceDefinition.apiextensions.k8s.io "securitycontextconstraints.security.openshift.io" is invalid: [spec.additionalPrinterColumns[0].JSONPath: Required value, spec.additionalPrinterColumns[1].JSONPath: Required value, spec.additionalPrinterColumns[2].JSONPath: Required value, spec.additionalPrinterColumns[3].JSONPath: Required value, spec.additionalPrinterColumns[4].JSONPath: Required value, spec.additionalPrinterColumns[5].JSONPath: Required value, spec.additionalPrinterColumns[6].JSONPath: Required value, spec.additionalPrinterColumns[7].JSONPath: Required value, spec.additionalPrinterColumns[8].JSONPath: Required value]
```

**Comment by ingvagabund** [comment]
@umohnani8 https://github.com/openshift/api/pull/811 should fix it

**Comment by soltysh** [comment]
/hold
until we get fixes from https://github.com/openshift/api/pull/811

**Comment by umohnani8** [comment]
re-vendored with https://github.com/openshift/api/pull/811

**Pull request merged**
