### PR TITLE
Revert config/v1/Node crd.yaml

### PR DESCRIPTION
**Pull request by swghosh**
Revert config/v1/Node crd.yaml by re-vendoring [o/api](https://github.com/openshift/api/) from a forked branch that reverts config-node CRD in order to check if our CI can pass an e2e-upgrade test.

- changes vendored from openshift/api#1160

Signed-off-by: Swarup Ghosh <swghosh@redhat.com>

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/approve

**Comment by candita** [comment]
BZ https://bugzilla.redhat.com/show_bug.cgi?id=2039256 depends on this merge.

**Pull request merged**
