### PR TITLE
MON-3774: add Collection Profiles feature-gate

### PR DESCRIPTION
**Pull request by rexagod**
Blocks https://github.com/openshift/cluster-monitoring-operator/pull/2153 (need [`configv1.FeatureGateCollectionProfiles`](https://github.com/openshift/cluster-monitoring-operator/pull/2153/files#diff-99c0290799daf9abc6240df64063e20bfaf67b371577b67ac7eec6f4725622ffR439)).

***

cc @jan--f

### CODE REVIEW

**Comment by rexagod** [comment]
Failures seem to stem from a discrepancy between https://github.com/openshift/api/blob/f608b5d33c00c4c135926ea3a9d77f1839683b80/config/v1/types_feature.go#L164 and https://github.com/openshift/api/commit/8cd1259c02b1718b4ec44aff6e8d71d1668d809c#diff-503cbb11f85749eb9ced1d2fcebdd1474b8df9ef32be2d845673838de8b7ff0cR144.

**Comment by deads2k** [comment]
this isn't needed for featuregate changes.  See your change already in featuregates: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-release-master-ci-4.16-e2e-aws-sdn-serial/1773251925546897408/artifacts/e2e-aws-sdn-serial/gather-extra/artifacts/featuregate.json

nightlies need to catch up

**Pull request closed without merging**
