### PR TITLE
add cluster resource quota resources

### PR DESCRIPTION
**Pull request by mfojtik**
depends on https://github.com/openshift/origin/pull/22277

/hold

### CODE REVIEW

**Comment by mfojtik** [comment]
@deads2k looks like we won't be able to keep the group name?

```
Mar 08 13:15:07 ip-10-0-14-27 bootkube.sh[4537]: Failed to create apiextensions.k8s.io/v1beta1, Resource=customresourcedefinitions: CustomResourceDefinition.apiextensions.k8s.io "quota.openshift.io" is invalid: metadata.name: Invalid value: "quota.openshift.io": must be spec.names.plural+"."+spec.group
```

**Comment by mfojtik** [comment]
@deads2k i was expecting this to explode?

**Comment by deads2k** [comment]
looks plausible, though I suspect that we'll end up having to fix the validation issues.

/lgtm

**Comment by mfojtik** [comment]
@deads2k validation fixes: https://github.com/openshift/api/pull/267

**Pull request merged**
