### PR TITLE
Add CRD and empty resource for OperatorHub config

### PR DESCRIPTION
**Pull request by aravindhp**
- bump (*) for api/config changes 
- Add CRD and empty resource for OperatorHub config

### CODE REVIEW

**Comment by aravindhp** [comment]
OpenShift api vendor bump and `make update-codegen` needs to be run to update this PR after https://github.com/openshift/api/pull/388 merges.

**Comment by aravindhp** [comment]
/hold cancel

This PR is now ready for review.

**Comment by damemi** [comment]
/lgtm
looks like a proper api bump/validation codegen

**Comment by smarterclayton** [comment]
/hold

I had a few questions on the CRD, please answer and then I'll unhold and approve

**Pull request merged**
