### PR TITLE
Add back all empty custom resources (including authentication)

### PR DESCRIPTION
**Pull request by enj**
Signed-off-by: Monis Khan <mkhan@redhat.com>

Requires https://github.com/openshift/cluster-kube-apiserver-operator/pull/399

@openshift/sig-auth @openshift/sig-master

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm
/hold

holding for prereq

**Comment by enj** [comment]
/retest

I cannot tell if the KCM crash loop is related.

**Pull request merged**
