### PR TITLE
bug 1871890: add current profile annotations to CVO manifests

### PR DESCRIPTION
**Pull request by deads2k**
This is matches https://github.com/openshift/enhancements/pull/414 and doesn't change existing behavior

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
This should be good to go now that https://github.com/openshift/release/pull/11184 merged
/lgtm
/retest

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by retroflexer** [comment]
Opened a new PR https://github.com/openshift/cluster-config-operator/pull/156/files to rebase and supersede this PR.

/close

**Pull request closed without merging**
