### PR TITLE
Bump(o/client-go); Add empty config/v1/node/cluster object

### PR DESCRIPTION
**Pull request by swghosh**
1. ~~Includes changes from:~~
    - ~~openshift/api#1140~~
    -  ~~openshift/api#1143~~
2. Added empty resource "config/v1/node/cluster" with empty spec
    - in favour of [Worker Latency Profiles EP](https://github.com/openshift/enhancements/blob/master/enhancements/worker-latency-profile/worker-latency-profile.md#api-extensions), [CGroupsV2 Enablement EP](https://github.com/openshift/enhancements/blob/master/enhancements/machine-config/mco-cgroupsv2-support.md#api-extensions)

[Updated]

3. ~~Include changes from openshift/api upto:~~
    - ~~openshift/api#1165~~

PS: https://github.com/openshift/api/pull/1160#issuecomment-1090371608

[Updated]

3. was already taken care of in openshift/cluster-config-operator#243
4. bump(client-go) upto openshift/client-go#210

Signed-off-by: Sai Ramesh Vanka <svanka@redhat.com>
Signed-off-by: Swarup Ghosh <swghosh@redhat.com>

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm

**Comment by swghosh** [comment]
/remove-hold (openshift/client-go#210 merged; depedency updated in 28db3f40dc2d70cca38df98fb74a334d7f697e5a)

**Pull request merged**
