### PR TITLE
[release-4.15] OCPBUGS-36151: Set required-scc for openshift workloads

### PR DESCRIPTION
**Pull request by kramaranya**
[OCPBUGS-36151](https://issues.redhat.com/browse/OCPBUGS-36151)

Manual cherry-pick of #410

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/approve
/label backport-risk-assessed

**Comment by xingxingxia** [comment]
Checked current 4.15 env:
```
$ oc get po -n openshift-config-operator -o yaml | grep scc
      openshift.io/scc: nonroot-v2
```
So, it is good for the PR to pin it to nonroot-v2.
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
