### PR TITLE
add image references

### PR DESCRIPTION
**Pull request by mfojtik**

### CODE REVIEW

**Comment by mfojtik** [comment]
(i think the e2e-aws will be broken now as we won't have the openshift-config namespace, but I can be surprised :-)

**Comment by deads2k** [comment]
wait for e2e-aws then merge

**Comment by mfojtik** [comment]
@deads2k feel free to merge if i'm out, rekick the installer PR after ~1h when this land.

**Comment by mfojtik** [comment]
e2e-aws is green, merging.

**Pull request merged**
