### PR TITLE
Bug 2043709: fix component-base logging flags

### PR DESCRIPTION
**Pull request by eggfoobar**
updated to use component-base/cli
component-base/cli addresses appending logging flags to command line

### CODE REVIEW

**Review by soltysh — CHANGES_REQUESTED** [review]
/hold
Can we do that similarly to https://github.com/openshift/cluster-kube-apiserver-operator/commit/ffb092644a35398a8b848522a96f60ac5a7297ef which makes this a whole lot simpler overall.

**Comment by eggfoobar** [comment]
Hey @soltysh, I updated the PR with the changes, but @deads2k had some questions where I had this update in a previous PR that I want to make sure we close the loop on.

https://github.com/openshift/cluster-config-operator/pull/227#discussion_r770676711
https://github.com/openshift/cluster-config-operator/pull/227#discussion_r770674079

**Comment by eggfoobar** [comment]
Hey @soltysh this should be good for another look, updated and squashed the commit to reflect the change

**Review by soltysh — APPROVED** [review]
/lgtm
/hold cancel

**Comment by soltysh** [comment]
overriding the valid bug, since the bot has a problem with assigning qe
/remove-label bugzilla/invalid-bug
/label bugzilla/valid-bug

**Pull request merged**
