### PR TITLE
update openshift/api for types and gates

### PR DESCRIPTION
**Pull request by deads2k**

### CODE REVIEW

**Comment by patrickdillon** [comment]
> /hold [openshift/api#1480](https://github.com/openshift/api/pull/1480)

Feel free to drop the hold, just wanted to note that I caught this and perhaps it would be easier to fix then revendor

**Comment by deads2k** [comment]
/hold cancel

open another with the new update.

**Comment by deads2k** [comment]
adds featuregates to allow features to isolate.

**Comment by patrickdillon** [comment]
> /hold cancel
> 
> open another with the new update.

Reopened https://github.com/openshift/cluster-config-operator/pull/314

**Pull request merged**
