### PR TITLE
Add AzureStack support

### PR DESCRIPTION
**Pull request by patrickdillon**
Adds AzureStack as a valid cloud environment.

Depends on openshift/api#860

WIP as currently using personal branch.

cc @staebler 
cc @jhixson74

### CODE REVIEW

**Review by staebler — COMMENTED** [review]
This looks good to me once the api PR merges.

**Comment by patrickdillon** [comment]
/reopen

not sure why this closed

**Comment by patrickdillon** [comment]
revendored now that API has merged

@deads2k PTAL for approve and LGTM

Will need follow up work in a separate PR to keep endpoints configmap in sync with API infra object

**Pull request merged**
