### PR TITLE
CFE-857: Update openshift/api package to latest version

### PR DESCRIPTION
**Pull request by bharath-b-rh**
PR is for updating the `openshift/api` package to the latest version which contains the API changes for supporting GCP tags in `Machine` and `MachineSet` APIs made in https://github.com/openshift/api/pull/1506

Updating `openshift/api` requires updating below packages to latest as well
- k8s.io/client-go
- k8s.io/apimachinery
- k8s.io/api
- k8s.io/apiserver
- github.com/openshift/client-go

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Making changes to the GCP Machine Provider Spec does not require an update to cluster-config-operator

**Comment by bharath-b-rh** [comment]
Updating GCPMachineProviderSpec requires package update in machine-api-operator, and not here. Hence closing this PR.

**Pull request closed without merging**
