### PR TITLE
NO-JIRA: pkg/cmd/render/config: Remove ReadFeatureGateV1OrDie

### PR DESCRIPTION
**Pull request by wking**
The last consumer was removed in d1874f8b2f (#309).

### CODE REVIEW

**Comment by wking** [comment]
Lots of [`Job execution failed: Pod scheduling timeout`][1], but that's a build-cluster issue, not a reflection on this pull.

/retest-required

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-config-operator/361/pull-ci-openshift-cluster-config-operator-master-verify/1712753258381971456

**Comment by JoelSpeed** [comment]
/retitle NO-JIRA: pkg/cmd/render/config: Remove ReadFeatureGateV1OrDie

**Comment by JoelSpeed** [comment]
Given the context of this PR, I think we are safe to override
/override ci/prow/e2e-aws-serial-techpreview

**Pull request merged**
