### PR TITLE
OCPBUGS-20164: Remove Build CRD

### PR DESCRIPTION
**Pull request by adambkaplan**
The Build CRD is no longer included in cluster-config-operator's manifests. This will be owned and deployed by
openshift-controller-manager-operator moving forward.

Might depend on https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/306 merging first.

### CODE REVIEW

**Comment by adambkaplan** [comment]
@bparees @wking my manual test results of this PR with `aws,no-capabilities` cluster bot:

1. No `build.openshift.io/v1` API resources
2. No custom resource _instances_ of `build.config.openshift.io/v1`
3. Custom resource definition of `build.config.openshift.io` still exsits.

```sh
$ oc get build -A
No resources found
$ oc get build.openshift.io
error: the server doesn't have a resource type "build"
$ oc get build.config.openshift.io
No resources found
$ oc get crds | grep "build"
builds.config.openshift.io                                        2023-10-11T17:13:28Z
$ oc api-resources | grep build
builds                                                                                                                       config.openshift.io/v1                        false        Build
```

Do we ship this as an early z-stream bug fix, and deal with the builds.config.openshift.io CRD in 4.15?

**Comment by adambkaplan** [comment]
@bparees @wking same result after adding the annotation to the empty-resources in openshift/api.

At this point we're past "quick fix" and entering "there's missing logic." Since we already have cruft related to the builds capability (see https://issues.redhat.com/browse/BUILD-726), do we merge this in as a quick fix and deal with the build CRD creation in 4.15?

**Comment by wking** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.15-e2e-aws-ovn-no-capabilities

**Comment by wking** [comment]
[`/payload-job` run][1]:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/openshift-cluster-config-operator-360-ci-4.15-e2e-aws-ovn-no-capabilities/1712240646447697920/artifacts/e2e-aws-ovn-no-capabilities/gather-must-gather/artifacts/must-gather.tar | tar xOz 60d093a4c518ddd700e5fad91954489579777836e49c5249bfdb28dc53fcaf01/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/builds.config.openshift.io.yaml | yaml2json | jq -r '.metadata.managedFields[] | select(.subresource != "status") | .time + " " + .operation + " " + .manager'
2023-10-11T23:12:04Z Update cluster-bootstrap
```

So this is still getting into the cluster at bootstrap time, via the config `render` command, and we'll need something like my #362 ugly hack, or a nicer way to tell the config operator "the Build CRD and empty custom resource don't need to be rendered at bootstrap-time". As seen in #362, the CVO will still pick up the manifests for these resources from the config operator's `/manifests/...` and ensure they get into the cluster before we declare install-complete. And there's nothing bootstrap-time that needs them there before the CVO pushes them in.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-cluster-config-operator-360-ci-4.15-e2e-aws-ovn-no-capabilities/1712240646447697920

**Comment by adambkaplan** [comment]
Paired with https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/306, and bumping api with https://github.com/openshift/api/pull/1618, this removes the Build CRD.

**Comment by bparees** [comment]
/hold

waiting for https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/306

**Comment by wking** [comment]
[build-cluster capacity flake][1]:

/test ci/prow/e2e-aws-serial-techpreview

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-config-operator/360/pull-ci-openshift-cluster-config-operator-master-e2e-aws-serial-techpreview/1712581810300391424#1:build-log.txt%3A42-47

**Pull request merged**
