### PR TITLE
Bug 2072739: [release-4.10] Bump openshift/api to a83e6f8f1d

### PR DESCRIPTION
**Pull request by candita**
Backport of https://bugzilla.redhat.com/show_bug.cgi?id=2072739 requires backport of the api bump as well.

### CODE REVIEW

**Comment by quarterpin** [comment]
/label qe-approved
Verified via pre-merge test process. For more details refer to: https://bugzilla.redhat.com/show_bug.cgi?id=2072739#c9

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Comment by candita** [comment]
@gangwgr could you please take a look and add the `cherry-pick-approved` label?

**Pull request merged**
