### PR TITLE
Add Proxy CRD

### PR DESCRIPTION
**Pull request by adambkaplan**

### CODE REVIEW

**Comment by adambkaplan** [comment]
/assign @deads2k 

fyi @bparees @coreydaley

**Comment by adambkaplan** [comment]
/hold

@deads2k this API object was added to house cluster-wide proxy config, but as far as I'm aware nothing creates or consumes it (I could be wrong...)

**Comment by DanyC97** [comment]
@adambkaplan i suspect this can be close in favour of #66 ?

**Comment by adambkaplan** [comment]
/close

Replaced by #66

**Pull request closed without merging**
