### PR TITLE
SPLAT-1400: promote vSphere control plane machinesets from tech preview

### PR DESCRIPTION
**Pull request by rvanderp3**

### CODE REVIEW

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-csi openshift/cluster-control-plane-machine-set-operator/#272

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.16-e2e-vsphere-ovn-csi openshift/cluster-control-plane-machine-set-operator#272

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-csi https://github.com/openshift/cluster-control-plane-machine-set-operator/pull/272

**Comment by rvanderp3** [comment]
/payload-job-with-prs periodic-ci-openshift-release-master-nightly-4.16-e2e-aws-csi openshift/cluster-control-plane-machine-set-operator#272

**Comment by rvanderp3** [comment]
/hold

setting hold while payload tests run

**Comment by rvanderp3** [comment]
payload tests look good

**Comment by JoelSpeed** [comment]
/approve

Merging because this is a useful bump, thanks, but for the future, when dealing with feature gates, it's no longer required to bump this repo. It all lands directly in the payload via o/api now

**Comment by rvanderp3** [comment]
> /approve
> 
> Merging because this is a useful bump, thanks, but for the future, when dealing with feature gates, it's no longer required to bump this repo. It all lands directly in the payload via o/api now

Thanks! I was not aware of that.

**Pull request merged**
