### PR TITLE
Bug 2033536: vendor: update openshift/api to include alibaba CRD update

### PR DESCRIPTION
**Pull request by kwoodson**
Updating to the latest openshift/api types.

The latest infrastructure types were updated and need to be brought inline with the installer.

### CODE REVIEW

**Comment by mtulio** [comment]
Cluster running as expected after that update. API update https://github.com/openshift/api/pull/1088
/lgtm

**Comment by kwoodson** [comment]
Cluster create occurred successfully:
```
INFO Install complete!                            
INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/home/kwoodson/tmp/alibaba/cluster/auth/kubeconfig' 
INFO Access the OpenShift web-console here: https://console-openshift-console.apps.test.alicloud-dev.devcluster.openshift.com 
INFO Login to the console with user: "kubeadmin", and password: "xxxxxx" 
DEBUG Time elapsed per stage:                      
DEBUG            cluster: 2m44s                    
DEBUG          bootstrap: 1m7s                     
DEBUG Bootstrap Complete: 14m17s                   
DEBUG                API: 3m5s                     
DEBUG  Cluster Operators: 17m27s                   
INFO Time elapsed: 35m41s                         
```
```
NAME                                 STATUS   ROLES    AGE   VERSION
test-mdx4k-master-0                  Ready	master   31m   v1.22.1+6859754
test-mdx4k-master-1                  Ready	master   33m   v1.22.1+6859754
test-mdx4k-master-2                  Ready	master   33m   v1.22.1+6859754
test-mdx4k-worker-us-east-1a-vpwl8   Ready    worker   20m   v1.22.1+6859754
test-mdx4k-worker-us-east-1b-89vxk   Ready    worker   20m   v1.22.1+6859754
test-mdx4k-worker-us-east-1b-cs59j   Ready    worker   19m   v1.22.1+6859754
NAME                                 PHASE     TYPE            REGION	   ZONE         AGE
test-mdx4k-master-0                  Running   ecs.g6.xlarge   us-east-1   us-east-1b   34m
test-mdx4k-master-1                  Running   ecs.g6.xlarge   us-east-1   us-east-1a   34m
test-mdx4k-master-2                  Running   ecs.g6.xlarge   us-east-1   us-east-1b   34m
test-mdx4k-worker-us-east-1a-vpwl8   Running   ecs.g6.large    us-east-1   us-east-1a   28m
test-mdx4k-worker-us-east-1b-89vxk   Running   ecs.g6.large    us-east-1   us-east-1b   28m
test-mdx4k-worker-us-east-1b-cs59j   Running   ecs.g6.large    us-east-1   us-east-1b   28m
```

This also requires openshift/machine-config-operator/pull/2884

**Comment by kwoodson** [comment]
Retested latest changes. Everything looks healthy:
```
NAME                                 STATUS   ROLES    AGE   VERSION
test-nf84w-master-0                  Ready    master   31m   v1.22.1+6859754
test-nf84w-master-1                  Ready    master   30m   v1.22.1+6859754
test-nf84w-master-2                  Ready    master   32m   v1.22.1+6859754
test-nf84w-worker-us-east-1a-vv5g2   Ready    worker   19m   v1.22.1+6859754
test-nf84w-worker-us-east-1b-qxjsp   Ready    worker   14m   v1.22.1+6859754
test-nf84w-worker-us-east-1b-zx4d2   Ready    worker   14m   v1.22.1+6859754
NAME                                 PHASE     TYPE            REGION	   ZONE         AGE
test-nf84w-master-0                  Running   ecs.g6.xlarge   us-east-1   us-east-1b   33m
test-nf84w-master-1                  Running   ecs.g6.xlarge   us-east-1   us-east-1a   33m
test-nf84w-master-2                  Running   ecs.g6.xlarge   us-east-1   us-east-1b   33m
test-nf84w-worker-us-east-1a-vv5g2   Running   ecs.g6.large    us-east-1   us-east-1a   26m
test-nf84w-worker-us-east-1b-qxjsp   Running   ecs.g6.large    us-east-1   us-east-1b   26m
test-nf84w-worker-us-east-1b-zx4d2   Running   ecs.g6.large    us-east-1   us-east-1b   26m
```
```
INFO Install complete!                            
INFO To access the cluster as the system:admin user when using 'oc', run 'export KUBECONFIG=/home/kwoodson/tmp/alibaba/cluster/auth/kubeconfig' 
INFO Access the OpenShift web-console here: https://console-openshift-console.apps.test.alicloud-dev.devcluster.openshift.com 
INFO Login to the console with user: "kubeadmin", and password: "xxxxx" 
DEBUG Time elapsed per stage:                      
DEBUG            cluster: 2m52s                    
DEBUG          bootstrap: 1m10s                    
DEBUG Bootstrap Complete: 14m15s                   
DEBUG                API: 3m0s                     
DEBUG  Cluster Operators: 22m27s                   
INFO Time elapsed: 40m49s                         

```

**Comment by tkashem** [comment]
/lgtm
/approve

Thanks!

**Comment by tkashem** [comment]
/hold

@soltysh is this safe to merge before the rebase PR https://github.com/openshift/kubernetes/pull/1087  lands?

**Review by soltysh — APPROVED** [review]
> @soltysh is this safe to merge before the rebase PR [openshift/kubernetes#1087](https://github.com/openshift/kubernetes/pull/1087) lands?

No objections

/hold cancel

/lgtm
/approve

**Pull request merged**
