### PR TITLE
Bug 1825944: kube_cloud_config: pass correct sourcekey to the transformers

### PR DESCRIPTION
**Pull request by abhinavdahiya**
/test e2e-gcp
/test e2e-azure

### CODE REVIEW

**Comment by abhinavdahiya** [comment]
/hold

need to make sure gcp, azure work correctly.

**Comment by abhinavdahiya** [comment]
/bugzillla refresh

/test e2e-gcp
/test e2e-azure

> https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-config-operator/128/pull-ci-openshift-cluster-config-operator-master-e2e-azure/1/artifacts/e2e-azure/configmaps.json
```
        {
            "apiVersion": "v1",
            "data": {
                "cloud.conf": "{\n\t\"cloud\": \"AzurePublicCloud\",\n\t\"tenantId\": \"6047c7e9-b2ad-488d-a54e-dc3f6be6a7ee\",\n\t\"aadClientId\": \"\",\n\t\"aadClientSecret\": \"\",\n\t\"aadClientCertPath\": \"\",\n\t\"aadClientCertPassword\": \"\",\n\t\"useManagedIdentityExtension\": true,\n\t\"userAssignedIdentityID\": \"\",\n\t\"subscriptionId\": \"d38f1e38-4bed-438e-b227-833f997adf6a\",\n\t\"resourceGroup\": \"ci-op-s3j175fs-371be-mbn5k-rg\",\n\t\"location\": \"eastus2\",\n\t\"vnetName\": \"ci-op-s3j175fs-371be-mbn5k-vnet\",\n\t\"vnetResourceGroup\": \"ci-op-s3j175fs-371be-mbn5k-rg\",\n\t\"subnetName\": \"ci-op-s3j175fs-371be-mbn5k-worker-subnet\",\n\t\"securityGroupName\": \"ci-op-s3j175fs-371be-mbn5k-node-nsg\",\n\t\"routeTableName\": \"ci-op-s3j175fs-371be-mbn5k-node-routetable\",\n\t\"primaryAvailabilitySetName\": \"\",\n\t\"vmType\": \"\",\n\t\"primaryScaleSetName\": \"\",\n\t\"cloudProviderBackoff\": true,\n\t\"cloudProviderBackoffRetries\": 0,\n\t\"cloudProviderBackoffExponent\": 0,\n\t\"cloudProviderBackoffDuration\": 6,\n\t\"cloudProviderBackoffJitter\": 0,\n\t\"cloudProviderRateLimit\": true,\n\t\"cloudProviderRateLimitQPS\": 6,\n\t\"cloudProviderRateLimitBucket\": 10,\n\t\"cloudProviderRateLimitQPSWrite\": 6,\n\t\"cloudProviderRateLimitBucketWrite\": 10,\n\t\"useInstanceMetadata\": true,\n\t\"loadBalancerSku\": \"standard\",\n\t\"excludeMasterFromStandardLB\": null,\n\t\"disableOutboundSNAT\": null,\n\t\"maximumLoadBalancerRuleCount\": 0\n}\n"
            },
            "kind": "ConfigMap",
            "metadata": {
                "creationTimestamp": "2020-04-21T17:41:32Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:data": {
                                ".": {},
                                "f:cloud.conf": {}
                            }
                        },
                        "manager": "cluster-config-operator",
                        "operation": "Update",
                        "time": "2020-04-21T17:41:32Z"
                    }
                ],
                "name": "kube-cloud-config",
                "namespace": "openshift-config-managed",
                "resourceVersion": "14588",
                "selfLink": "/api/v1/namespaces/openshift-config-managed/configmaps/kube-cloud-config",
                "uid": "92bb26b3-7cad-4b45-bbaa-c214fa5ad2c9"
            }
        },
```

> https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-config-operator/128/pull-ci-openshift-cluster-config-operator-master-e2e-gcp/1/artifacts/e2e-gcp/configmaps.json
```
        {
            "apiVersion": "v1",
            "data": {
                "cloud.conf": "[global]\nproject-id      = openshift-gce-devel-ci\nregional        = true\nmultizone       = true\nnode-tags       = ci-op-mjbwr-master\nnode-tags       = ci-op-mjbwr-worker\nnode-instance-prefix = ci-op-mjbwr\nexternal-instance-groups-prefix = ci-op-mjbwr\nsubnetwork-name = ci-op-mjbwr-worker-subnet\n\n"
            },
            "kind": "ConfigMap",
            "metadata": {
                "creationTimestamp": "2020-04-21T17:46:12Z",
                "managedFields": [
                    {
                        "apiVersion": "v1",
                        "fieldsType": "FieldsV1",
                        "fieldsV1": {
                            "f:data": {
                                ".": {},
                                "f:cloud.conf": {}
                            }
                        },
                        "manager": "cluster-config-operator",
                        "operation": "Update",
                        "time": "2020-04-21T17:46:12Z"
                    }
                ],
                "name": "kube-cloud-config",
                "namespace": "openshift-config-managed",
                "resourceVersion": "17524",
                "selfLink": "/api/v1/namespaces/openshift-config-managed/configmaps/kube-cloud-config",
                "uid": "d250e640-4957-4060-905d-94c2a510bf34"
            }
        },
```

**Comment by sinnykumari** [comment]
Using clusterbot checked-
- cluster install succeeded with this PR and https://github.com/openshift/machine-config-operator/pull/1658
- [upgrade](https://prow.svc.ci.openshift.org/view/gcs/origin-ci-test/logs/release-openshift-origin-installer-e2e-gcp-upgrade/645)  from 4.5 to this PR + https://github.com/openshift/machine-config-operator/pull/1658 went well

**Pull request merged**
