### PR TITLE
add empty CRs

### PR DESCRIPTION
**Pull request by deads2k**
from https://github.com/openshift/cluster-config-operator/pull/38

### CODE REVIEW

**Comment by rphillips** [comment]
The error doesn't look like a MCO rendering error... going to...

/retest

**Comment by deads2k** [comment]
@rphillips it does

```
                    {
                        "lastTransitionTime": "2019-04-11T19:46:50Z",
                        "message": "Failed to resync 0.0.1-2019-04-11-192548 because: error pool master is not ready, retrying. Status: (total: 3, updated: 0, unavailable: 1)",
                        "reason": "error pool master is not ready, retrying. Status: (total: 3, updated: 0, unavailable: 1)",
                        "status": "True",
                        "type": "Failing"
                    }
                ],
```
https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-config-operator/39/pull-ci-openshift-cluster-config-operator-master-e2e-aws/168/artifacts/e2e-aws/clusteroperators.json

**Comment by deads2k** [comment]
@rphillips opened https://bugzilla.redhat.com/show_bug.cgi?id=1699353 to help track it.

**Comment by sjenning** [comment]
This has failed e2e-aws the same way every time
```
cluster operator machine-config is reporting a failure: Failed to resync 0.0.1-2019-04-15-163916 because: error pool master is not ready, retrying. Status: (total: 3, updated: 0, unavailable: 1): timed out waiting for the condition"
```
Do we know what is wrong here?

**Comment by rphillips** [comment]
I don't think this PR has any chance of succeeding without https://github.com/openshift/machine-config-operator/pull/644

**Comment by sjenning** [comment]
why did the bot close this?

**Comment by sjenning** [comment]
/retest
now that https://github.com/openshift/machine-config-operator/pull/644 is merged

**Comment by rphillips** [comment]
@deads2k all tests pass... ready to rock n' roll 🎸

**Pull request merged**
