### PR TITLE
Generate operator/v1alpha1 CRDs, update for https://github.com/openshift/api/pull/384

### PR DESCRIPTION
**Pull request by mtrmac**
<s>DO NOT MERGE: This includes UNMERGED #70, and will need to be rebased on top of it.</s>

This PR updates vendor openshift/api for https://github.com/openshift/api/pull/384 , adds generation of the CRDs for the operator/v1alpha1 namespace (or was it omitted intentionally?) and runs the CRD generator.

### CODE REVIEW

**Comment by damemi** [comment]
@mtrmac thanks for catching that missing `operator/v1alpha1`, it definitely wasn't intentional. #70 has been tagged and will hopefully merge soon

**Comment by mtrmac** [comment]
Rebased on top of merged #70, PTAL.

**Comment by umohnani8** [comment]
@sttts this is ready to be merged, PTAL.

**Comment by umohnani8** [comment]
@deads2k @abhinavdahiya PTAL

**Comment by mrunalp** [comment]
@deads2k @sttts ptal.

**Pull request merged**
