### PR TITLE
CFE-921: Update openshift/api package to latest version

### PR DESCRIPTION
**Pull request by bharath-b-rh**
This is a manual cherry-pick of https://github.com/openshift/cluster-config-operator/pull/423

/assign bharath-b-rh

### CODE REVIEW

**Comment by deads2k** [comment]
shouldn't be needed, but it looks ok.

**Comment by bharath-b-rh** [comment]
PR was mainly created to sync the feature gates. And since these changes aren't needed for the actual purpose, closing it.

**Pull request closed without merging**
