### PR TITLE
create bootstrap-manifests directory

### PR DESCRIPTION
**Pull request by deads2k**
this may solve the issue from https://github.com/openshift/installer/pull/1187

/assign @mfojtik

### CODE REVIEW

**Comment by sttts** [comment]
This is not enough.

the Dockerfile has to copy `manifests/*` to `/usr/share/bootkube/manifests/manifests`. Note the second "manifests".

`/usr/share/bootkube/manifests` should be better called `/usr/share/bootkube/templates`. Then it would be clearer.

**Comment by deads2k** [comment]
isntall completed merging

**Pull request merged**
