### PR TITLE
OCPBUGS-13547: Promote Azure CCM from TPNU to default

### PR DESCRIPTION
**Pull request by JoelSpeed**
This promotes the Azure CCM from TechPreviewNoUpgrade to default

/hold 

We need to thoroughly test this and make sure all prior known fixes are merged before this can be merged

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/test e2e-azure

Seems there's some infrastructure related issue causing failures

**Comment by JoelSpeed** [comment]
Network operator is going degraded because of some panic in the internals of the http server in the last run, doesn't look like that's desirable
/test e2e-azure

**Comment by JoelSpeed** [comment]
Azure E2E failed this time in cluster teardown, but the tests themselves passed, lets try some payload tests
/payload-job periodic-ci-openshift-cluster-control-plane-machine-set-operator-release-4.14-periodics-e2e-azure periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn periodic-ci-openshift-release-master-nightly-4.14-e2e-azure-sdn periodic-ci-openshift-release-master-ci-4.14-e2e-azure-sdn-upgrade periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade

**Comment by JoelSpeed** [comment]
Having reviewed the previous payload jobs, looks like a couple of minor/unrelated flakes caused failures, lets run some payload blocking tests to see if they find any issues
/payload 4.14 nightly blocking
/payload 4.14 ci blocking

**Comment by damdo** [comment]
We'll need rebasing for this in order to test it in combination with https://github.com/openshift/cloud-provider-azure/pull/76

**Comment by JoelSpeed** [comment]
Some required fixes are now in the latest nightly
/payload 4.14 nightly blocking
/payload 4.14 ci blocking

**Comment by JoelSpeed** [comment]
Azure CCM promotion was reverted last time because of https://issues.redhat.com/browse/OCPBUGS-11308
It was showing disruption on Azure micro upgrades, to prove that is now fixed, we can run an aggregate over the same job
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn-upgrade 10

**Comment by JoelSpeed** [comment]
The upgrade aggregation went green!
The regular one did not, 6 jobs passed, 4 failures:
* 1 run failed after 10 minutes - tried to install to a region unavailable for the account, infrastructure issue
* 1 run had issues with prometheus by the looks of it, something about reporting telemetry late, suspect it's unrelated
* 1 had only [5/6 machines become nodes](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-cluster-config-operator-307-ci-4.14-e2e-azure-ovn/1674078895764148224), the 6th machine failed to boot with the following error, this looks like it could be a MAPI issue
```
"failed to reconcile machine \"ci-op-m5y1z9gy-37915-km9cv-worker-westus-9d4gk\": failed to create vm ci-op-m5y1z9gy-37915-km9cv-worker-westus-9d4gk: failure sending request for machine ci-op-m5y1z9gy-37915-km9cv-worker-westus-9d4gk: cannot create vm: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=\u003cnil\u003e Code=\"ConflictingUserInput\" Message=\"Disk ci-op-m5y1z9gy-37915-km9cv-worker-westus-9d4gk_OSDisk already exists in resource group CI-OP-M5Y1Z9GY-37915-KM9CV-RG. Only CreateOption.Attach is supported.\" Target=\"/subscriptions/72e3a972-58b0-4afc-bd4f-da89b39ccebd/resourceGroups/ci-op-m5y1z9gy-37915-km9cv-rg/providers/Microsoft.Compute/disks/ci-op-m5y1z9gy-37915-km9cv-worker-westus-9d4gk_OSDisk\"
```
* The [final failed job](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-cluster-config-operator-307-ci-4.14-e2e-azure-ovn/1674078893880905728) seemed to fail spectacularly. It failed with 101 errors, most of which look like networking cancelled related errors. It failed after 90 minutes which seems a lot short than the other runs, perhaps the test pod got cancelled?

Going to try that again
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn 10

**Comment by JoelSpeed** [comment]
All went green this time, I think this is good to go

**Comment by JoelSpeed** [comment]
Spoke to TRT, they would like us to hold on this until the next EC build has been cut, will merge next week

**Comment by JoelSpeed** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn

**Comment by JoelSpeed** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn

Test pod failed to schedule

**Comment by JoelSpeed** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-azure-ovn 10

The canary I ran is using the latest CCM, so let's do this one more time to double check my latest fix hasn't broken anything

**Review by damdo — COMMENTED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
/hold cancel

API PR has merged and test runs from previous job show that the CCM is working as expected and is not causing the disruption that previously caused it to be reverted

**Comment by JoelSpeed** [comment]
/override ci/prow/e2e-aws-ovn-techpreview 

This PR does not affect AWS in any way, and especially not in techpreview. Failures were minor and related to OLM, so I'm confident not caused by this PR

**Pull request merged**
