### PR TITLE
Bump for RBR CRD, add nullables, Namespaced

### PR DESCRIPTION
**Pull request by sallyom**
@deads2k 
Same as [this](https://github.com/openshift/cluster-config-operator/pull/59), with a proper bump.

### CODE REVIEW

**Comment by sallyom** [comment]
e2e-aws failing `oc explain` tests: [this](https://github.com/openshift/origin/pull/22768) should fix.

**Comment by wking** [comment]
[e2e-aws][1]:

```
level=fatal msg="failed to initialize the cluster: Some cluster operators are still updating: authentication, console: timed out waiting for the condition"
```

[e2e-aws-upgrade][2]:

```
8 error level events were detected during this test run:

May 03 20:13:51.064 E clusterversion/version changed Failing to True: UpdatePayloadResourceInvalid: Could not update customresourcedefinition "rolebindingrestrictions.authorization.openshift.io" (7 of 349): the object is invalid, possibly due to local cluster configuration
...
fail [github.com/openshift/origin/test/e2e/upgrade/upgrade.go:133]: during upgrade
Expected error:
    <*errors.errorString | 0xc001491bd0>: {
        s: "Cluster did not complete upgrade: timed out waiting for the condition",
    }
    Cluster did not complete upgrade: timed out waiting for the condition
not to have occurred
...
Failing tests:

[Disruptive] Cluster upgrade should maintain a functioning cluster [Feature:ClusterUpgrade] [Suite:openshift] [Serial]
```

/retest

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-config-operator/61/pull-ci-openshift-cluster-config-operator-master-e2e-aws/302
[2]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-config-operator/61/pull-ci-openshift-cluster-config-operator-master-e2e-aws-upgrade/49

**Comment by wking** [comment]
That [last e2e-aws run][1] was flapping `Progressing`:

```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-config-operator/61/pull-ci-openshift-cluster-config-operator-master-e2e-aws/302/artifacts/e2e-aws/pods/openshift-authentication-operator_authentication-operator-599cd8f5b7-f7fx6_operator.log | gunzip | tail -n4

I0503 22:49:59.971959       1 event.go:221] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-authentication-operator", Name:"authentication-operator", UID:"107a5a83-6df1-11e9-8442-12f8f14b8da0", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'OperatorStatusChanged' Status for operator authentication changed: Degraded message changed from "Degraded: error checking current version: unable to check route health: failed to GET route: dial tcp: lookup integrated-oauth-server-openshift-authentication.apps.ci-op-l8w5d97q-2032a.origin-ci-int-aws.dev.rhcloud.com on 172.30.0.10:53: no such host" to "",Progressing changed from Unknown to False (""),Available changed from Unknown to True ("")
I0503 22:49:59.972202       1 status_controller.go:160] clusteroperator/authentication diff {"status":{"conditions":[{"lastTransitionTime":"2019-05-03T22:19:33Z","reason":"AsExpected","status":"False","type":"Degraded"},{"lastTransitionTime":"2019-05-03T22:49:59Z","reason":"AsExpected","status":"False","type":"Progressing"},{"lastTransitionTime":"2019-05-03T22:49:59Z","reason":"AsExpected","status":"True","type":"Available"},{"lastTransitionTime":"2019-05-03T22:19:32Z","reason":"NoData","status":"Unknown","type":"Upgradeable"}]}}
I0503 22:49:59.981042       1 event.go:221] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"openshift-authentication-operator", Name:"authentication-operator", UID:"107a5a83-6df1-11e9-8442-12f8f14b8da0", APIVersion:"apps/v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'OperatorStatusChanged' Status for operator authentication changed: Degraded message changed from "Degraded: error checking current version: unable to check route health: failed to GET route: dial tcp: lookup integrated-oauth-server-openshift-authentication.apps.ci-op-l8w5d97q-2032a.origin-ci-int-aws.dev.rhcloud.com on 172.30.0.10:53: no such host" to "",Progressing changed from Unknown to False (""),Available changed from Unknown to True ("")
```

[1]: https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-config-operator/61/pull-ci-openshift-cluster-config-operator-master-e2e-aws/302

**Comment by deads2k** [comment]
> [e2e-aws-upgrade](https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/openshift_cluster-config-operator/61/pull-ci-openshift-cluster-config-operator-master-e2e-aws-upgrade/49):

@wking the upgrade will never succeed because this change is illegal, but it's a mistake and we will merge anyway on a green e2e

**Pull request merged**
