### PR TITLE
 eliminate duplicate information

### PR DESCRIPTION
**Pull request by deads2k**
and hope I get an image.

### CODE REVIEW

**Comment by deads2k** [comment]
@tnozicka any idea what happened to our tide jobs?  https://github.com/openshift/cluster-config-operator/pull/4 had them....

**Comment by deads2k** [comment]
> @tnozicka any idea what happened to our tide jobs? #4 had them....

and they were just slow I guess

**Comment by deads2k** [comment]
I plan to merge this on green e2e-aws

**Comment by deads2k** [comment]
@abhinavdahiya can you give a pointer for where I integrate this into a render step?

**Comment by abhinavdahiya** [comment]
> @abhinavdahiya can you give a pointer for where I integrate this into a render step?

I correctly understand the output of render command, It will create the CRDs for `config.openshift.io` and only CRDs.


- lets add a render command before this [1] section that looks that outputs the CRDs to `manifests` directory.

- remove all the CRDs from installer
* https://github.com/openshift/installer/blob/master/data/data/manifests/bootkube/cluster-dns-01-crd.yaml
* https://github.com/openshift/installer/blob/master/data/data/manifests/bootkube/cluster-ingress-01-crd.yaml
* https://github.com/openshift/installer/blob/master/data/data/manifests/openshift/cluster-infrastructure-crd.yaml
* https://github.com/openshift/installer/blob/master/pkg/asset/templates/content/openshift/cluster-infrastructure-crd.go
* https://github.com/openshift/installer/blob/master/pkg/asset/manifests/dns.go#L68
* https://github.com/openshift/installer/blob/9e263e05896508752f185ec88c9592c66fdaf694/pkg/asset/manifests/infrastructure.go#L44
* https://github.com/openshift/installer/blob/master/pkg/asset/manifests/ingress.go#L69
* https://github.com/openshift/installer/pull/1013

[1] https://github.com/openshift/installer/blob/9e263e05896508752f185ec88c9592c66fdaf694/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L35-L51

**Comment by deads2k** [comment]
@abhinavdahiya so I actually duplicate this section: https://github.com/openshift/installer/blob/9e263e05896508752f185ec88c9592c66fdaf694/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L53-L73 ?

**Comment by abhinavdahiya** [comment]
> @abhinavdahiya so I actually duplicate this section: https://github.com/openshift/installer/blob/9e263e05896508752f185ec88c9592c66fdaf694/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L53-L73 ?

Yeah, that should be enough.

**Pull request merged**
