### PR TITLE
Fix config/v1 NetworkStatus spec

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by danwinship** [comment]
This (and by extension https://github.com/openshift/api/pull/237) seems wrong; we shouldn't be allowing `null` as a value here, we should be marking the fields `omitempty` (in which case the CRD doesn't need to be updated because it already doesn't require the array to exist or be non-empty)

**Comment by sttts** [comment]
@danwinship am fine with that. Installer uses null though.

**Comment by sttts** [comment]
@danwinship can you open pulls which are correct? My day is coming to an end here, and I won't be able to push that through.

**Comment by sttts** [comment]
With omitempty every writer of those objects (i.e. repos which marshal using openshift/api types), must be updated.

**Pull request merged**
