### PR TITLE
Bug 1732150: Update scheduler description

### PR DESCRIPTION
**Pull request by damemi**
Depends on https://github.com/openshift/api/pull/399

Updates the CRD description for scheduler config

### CODE REVIEW

**Comment by damemi** [comment]
/hold
this has a temporary bump of my fork for proof

**Comment by damemi** [comment]
cc @ravisantoshgudimetla 
when we decide on a good description this will be the PR to actually fix the BZ

**Comment by soltysh** [comment]
@damemi the api pr is tagged and should merge within next few minutes, please update this pr then.

**Pull request merged**
