### PR TITLE
Bug 1901535: Update openshift/api dependency

### PR DESCRIPTION
**Pull request by awgreene**

### CODE REVIEW

**Comment by awgreene** [comment]
/test e2e-upgrade

Error: `Error creating IAM instance profile ci-op-jwglwifp-bf329-dwkcn-bootstrap-profile: LimitExceeded: Cannot exceed quota for InstanceProfilesPerAccount: 1000`

**Comment by awgreene** [comment]
```* 3x kubelet: Container image "gcr.io/k8s-prow/sidecar:v20210317-3053d84953" already present on machine
* 2x kubelet: Error: context deadline exceeded
* 1x kubelet: Failed to inspect image "image-registry.openshift-image-registry.svc:5000/ci-op-3mzipdzs/stable@sha256:065d202214f9cb3f9c4ec36de81181824298dd9f5fdf416daf1a31e041f8ca02": rpc error: code = DeadlineExceeded desc = context deadline exceeded
 ```

/retest

**Comment by stlaz** [comment]
/retitle Bug 1901535: Update openshift/api dependency
/lgtm
/assign @mfojtik 

I'm going to connect this to a BZ of mine since it addresses it, too.

Assigning Michal for an approval.

**Pull request merged**
