### PR TITLE
RBRs are Namespaced, and more nullable, update CRD

### PR DESCRIPTION
**Pull request by sallyom**
@damemi  I don't think I'll need to make any corresponding api change.  I don't see any namespace comment in openshift/api, I see nonNamespace, though.   
@deads2k thanks for the tip.

### CODE REVIEW

**Comment by deads2k** [comment]
/retest

this will never pass upgrade jobs

**Comment by damemi** [comment]
@sallyom if it doesn't have `nonNamespaced`, the generator assumes it is namespaced.

Semi-related: I have a PR open to fix up some of these tags I noticed which could use a review if you have time: https://github.com/openshift/api/pull/302

**Comment by deads2k** [comment]
/lgtm

upgrade will not pass. this is expected.  Will merge on green e2e-aws

**Comment by sallyom** [comment]
closing in favor of [PR with proper bump](https://github.com/openshift/cluster-config-operator/pull/61)

**Pull request closed without merging**
