### PR TITLE
CCO-412: Bump API to promote azureWorkloadIdentity to defaultFeatures.

### PR DESCRIPTION
**Pull request by jstuever**
Bump OpenShift API to promote the azureWorkloadIdentity feature from the TechPreviewNoUpgrade featureSet to defaultFeatures.

Depends on https://github.com/openshift/api/pull/1563

### CODE REVIEW

**Comment by sdodson** [comment]
/approve
/cc @JoelSpeed
for code review, but i guess this needs a rebase after the api change lands anyway?

**Comment by JoelSpeed** [comment]
Needs a vendor update and is currently blocked by the unrevert in #348

**Comment by JoelSpeed** [comment]
@jstuever We merged a revert of the `validatingAdmissionPolicy` change into the API repo, can you update the vendor here to include the latest change so that we don't bring in that feature gate change

**Comment by jstuever** [comment]
> @jstuever We merged a revert of the `validatingAdmissionPolicy` change into the API repo, can you update the vendor here to include the latest change so that we don't bring in that feature gate change

Done. I'm concerned about the additional things also being brought over, such as k8s api bump to 0.28.1.

**Pull request merged**
