### PR TITLE
OCPCLOUD-2010: Remove feature gate for external platform

### PR DESCRIPTION
**Pull request by adriengentil**
Re-vendor openshift/api in order to move external platform feature out
of the feature gate.

x-ref: https://github.com/openshift/api/pull/1530

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Are there any jobs that can be run with this PR to prove the feature is working as expected?

**Comment by elmiko** [comment]
@JoelSpeed i don't think we have a ci job that exercises the external ccm in place yet

**Comment by adriengentil** [comment]
/retitle OCPCLOUD-2010: Remove feature gate for external platform

**Pull request merged**
