### PR TITLE
MCO-813: add MCN featuregate

### PR DESCRIPTION
**Pull request by cdoern**
bring in the MachineConfigNode featuregate to then be brought into the MCO.

Also bring in a few other API changes since the last bump.

### CODE REVIEW

**Comment by cdoern** [comment]
@tkashem PTAL! thanks

**Comment by cdoern** [comment]
@soltysh @JoelSpeed  can I please get some eyes on this? This feature is intended to be TechPreview in 4.15

**Review by JoelSpeed — COMMENTED** [review]
/lgtm

**Pull request merged**
