### PR TITLE
OCPCLOUD-1989: Promote GCP CCM from TPNU to default

### PR DESCRIPTION
**Pull request by JoelSpeed**
This promotes the GCP CCM from TechPreviewNoUpgrade to default

/hold

We need to thoroughly test this and make sure all prior known fixes are merged before this can be merged

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade 10
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade 10

**Comment by JoelSpeed** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-e2e-gcp-ovn-upgrade 10
/payload-aggregate periodic-ci-openshift-release-master-ci-4.14-upgrade-from-stable-4.13-e2e-gcp-ovn-rt-upgrade 10

**Comment by JoelSpeed** [comment]
Payload aggregate jobs are all being hit by a disruption poller pod issues at the moment, but I can see a revert went in to tackle this earlier, so will re-run once this hits a CI build and we get a green GCP CI job (also need to run 4.15 jobs not 4.14)

**Comment by JoelSpeed** [comment]
/payload-aggregate periodic-ci-openshift-release-master-ci-4.15-e2e-gcp-ovn-upgrade 10
/payload-aggregate periodic-ci-openshift-release-master-ci-4.15-upgrade-from-stable-4.14-e2e-gcp-ovn-rt-upgrade 10

**Review by damdo — COMMENTED** [review]
/lgtm

**Pull request merged**
