### PR TITLE
bump openshift/api to support new field controlPlaneToplogy in

### PR DESCRIPTION
**Pull request by ravidbro**
Infrastructure

Signed-off-by: Ravid Brown <ravid@redhat.com>

### CODE REVIEW

**Comment by deads2k** [comment]
/lgtm

You'll want to keep an eye on this to see if it goes green.

**Comment by deads2k** [comment]
for future reference, https://github.com/openshift/api/commit/670ac3fc997c2f1d19b8c29ef04f70d6e3d4a59e is current HEAD of master

**Comment by ravidbro** [comment]
> for future reference, [openshift/api@670ac3f](https://github.com/openshift/api/commit/670ac3fc997c2f1d19b8c29ef04f70d6e3d4a59e) is current HEAD of master

maybe I'm missing something but I think that this is the hash I put

**Pull request merged**
