### PR TITLE
Add SecurityContextConstraint CRD

### PR DESCRIPTION
**Pull request by sallyom**
Moving SCCs to CRDs 
see: https://github.com/openshift/origin/pull/22567
Bug 1698625

### CODE REVIEW

**Comment by stlaz** [comment]
In https://github.com/openshift/api/blob/master/security/v1/types.go#L23, most of the fields are marked as optional but are not anymore in the CRD?

**Comment by ericavonb** [comment]
/hold
until after beta release is cut

**Comment by sallyom** [comment]
waiting on this to clear e2e-aws: openshift/origin#22606

**Comment by sallyom** [comment]
closing in favor of https://github.com/openshift/cluster-config-operator/pull/51

**Pull request closed without merging**
