### PR TITLE
[release-4.14] OCPBUGS-20439: Remove Build CRD

### PR DESCRIPTION
**Pull request by adambkaplan**
Rename Build CRD yaml so that it is not included in cluster-config-operator's set of manifests. Build CRD will be owned and managed by openshift-controller-manager-operator moving forward.

Manual cherry-pick of #360, may require https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/307 to land first.

### CODE REVIEW

**Comment by bparees** [comment]
manually labeling this as valid-bug, we're going to merge out of order (merge to 4.14 first, then follow with 4.15) due to time constraints for getting this into 4.14.0. There is ample time to avoid any regression concerns.

**Comment by bparees** [comment]
/hold

needs to be updated w/ a proper bump from openshift/api once https://github.com/openshift/api/pull/1617 lands

**Comment by wking** [comment]
/payload-job periodic-ci-openshift-release-master-ci-4.14-e2e-aws-ovn-no-capabilities

**Comment by wking** [comment]
[`/payload-job` run][1]:

```console
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/openshift-cluster-config-operator-363-ci-4.14-e2e-aws-ovn-no-capabilities/1712294465357484032/artifacts/e2e-aws-ovn-no-capabilities/gather-must-gather/artifacts/must-gather.tar | tar tvz | grep builds.config
-rw------- 1006330000/root   26768 2023-10-11 21:03 registry-build01-ci-openshift-org-ci-op-0v5f3hgv-stable-sha256-9d4dcf33eebdeb01573a70cc4aa0f7f9e492a5f2d5cfdfd410d5bd00766302f8/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/builds.config.openshift.io.yaml
$ curl -s https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/openshift-cluster-config-operator-363-ci-4.14-e2e-aws-ovn-no-capabilities/1712294465357484032/artifacts/e2e-aws-ovn-no-capabilities/gather-must-gather/artifacts/must-gather.tar | tar xOz registry-build01-ci-openshift-org-ci-op-0v5f3hgv-stable-sha256-9d4dcf33eebdeb01573a70cc4aa0f7f9e492a5f2d5cfdfd410d5bd00766302f8/cluster-scoped-resources/apiextensions.k8s.io/customresourcedefinitions/builds.config.openshift.io.yaml | yaml2json | jq -r '.metadata.managedFields[] | select(.subresource != "status") | .time + " " + .operation + " " + .manager'
2023-10-12T02:48:10Z Update cluster-bootstrap
```

So this is still getting into the cluster at bootstrap time, via the config `render` command, and we'll need something like my #362 ugly hack, or a nicer way to tell the config operator "the Build CRD and empty custom resource don't need to be rendered at bootstrap-time".  As seen in #362, the CVO will still pick up the manifests for these resources from the config operator's `/manifests/...` and ensure they get into the cluster before we declare install-complete.  And there's nothing bootstrap-time that needs them there before the CVO pushes them in.

[1]: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/openshift-cluster-config-operator-363-ci-4.14-e2e-aws-ovn-no-capabilities/1712294465357484032

**Comment by bparees** [comment]
waiting on https://github.com/openshift/cluster-openshift-controller-manager-operator/pull/307

**Pull request merged**
