### PR TITLE
 [OCPNODE-521]Update go.mod api,client-go to register crd

### PR DESCRIPTION
**Pull request by QiWang19**
Update go.mod api,client-go to register crd ImageDigestMirrorSet, ImageTagMirrorSet.
- Epic: https://issues.redhat.com/browse/OCPNODE-521
- CRD ImageDigestMirrorSet implemented: https://github.com/openshift/machine-config-operator/pull/3037

Signed-off-by: Qi Wang <qiwan@redhat.com>

### CODE REVIEW

**Comment by QiWang19** [comment]
/hold 

hold since https://github.com/openshift/cluster-config-operator/pull/269 update of the api is on hold

**Comment by deads2k** [comment]
/hold

I think this is wedged for the same reason as https://github.com/openshift/cluster-config-operator/pull/269#issuecomment-1301179352

@mfojtik had a bugzilla reference last I recall.

**Comment by QiWang19** [comment]
@rvanderp3 said we can go ahead with this bump.

**Comment by mfojtik** [comment]
https://issues.redhat.com/browse/OCPBUGS-3123 is the issue, I think we can keep merging as we track this as 4.12.0 blocker now and @sanchezl is looking into fixing this.

**Comment by QiWang19** [comment]
> https://issues.redhat.com/browse/OCPBUGS-3123 is the issue, I think we can keep merging as we track this as 4.12.0 blocker now and @sanchezl is looking into fixing this.

@mfojtik thanks. @deads2k could you merge this?

**Pull request merged**
