### PR TITLE
bumped openshift API to have node object related changes

### PR DESCRIPTION
**Pull request by sairameshv**
/hold
This is a draft PR that contains the latest API changes w.r.t the "Node" object.
Reference: https://github.com/openshift/enhancements/blob/master/enhancements/worker-latency-profile/worker-latency-profile.md

### CODE REVIEW

**Comment by sairameshv** [comment]
cc: @harche @rphillips

**Comment by harche** [comment]
/cc @soltysh  

This is needed to support Worker Latency Profiles

**Pull request merged**
