### PR TITLE
add empty CRs

### PR DESCRIPTION
**Pull request by deads2k**
@bparees since you asked

I *think* this will avoid stomping.  The test-aws should fail if this clears values.

### CODE REVIEW

**Comment by bparees** [comment]
/lgtm
:crossed_fingers:

**Comment by bparees** [comment]
if this works we'll want to follow it up w/ one to create the default build resource

**Comment by deads2k** [comment]
/hold

thinking about the impact of this when combined with the render step.

**Comment by deads2k** [comment]
aws

/retest

**Comment by deads2k** [comment]
the dreaded sha sha

**Comment by abhinavdahiya** [comment]
@deads2k including these in `/manifests` means that CVO will empty out all the CRs continuously....

**Comment by bparees** [comment]
> @deads2k including these in `/manifests` means that CVO will empty out all the CRs continuously....

it's not merging/applying?

**Comment by abhinavdahiya** [comment]
> > @deads2k including these in `/manifests` means that CVO will empty out all the CRs continuously....
> 
> it's not merging/applying?

the `/manifests` is the desired, which according to this PR you want empty...

**Comment by abhinavdahiya** [comment]
> > > @deads2k including these in `/manifests` means that CVO will empty out all the CRs continuously....
> > 
> > 
> > it's not merging/applying?
> 
> the `/manifests` is the desired, which according to this PR you want empty...

/hold

**Comment by abhinavdahiya** [comment]
> > @deads2k including these in `/manifests` means that CVO will empty out all the CRs continuously....
> 
> it's not merging/applying?

https://github.com/openshift/cluster-version-operator/blob/0619e6cd016a14a0952542838b7f95eff2ddae43/pkg/cvo/internal/generic.go#L29-L58

**Comment by deads2k** [comment]
We'll sort it out tomorrow.  For items in config.openshift.io, I'm sure we can work out a spec/status update split.

**Comment by deads2k** [comment]
Alright, this may only put them out during a render.

**Comment by deads2k** [comment]
machien config

/retest

**Comment by deads2k** [comment]
looks to have worked.

**Comment by deads2k** [comment]
removing hold because these are longer part of the payload.

**Comment by wking** [comment]
```console
$ curl -s https://storage.googleapis.com/origin-ci-test/pr-logs/pull/openshift_cluster-config-operator/15/pull-ci-openshift-cluster-config-operator-master-e2e-aws/123/artifacts/e2e-aws/bootstrap/bootkube.service | tail -n2
Apr 08 18:16:12 ip-10-0-7-174 bootkube.sh[1343]: [#5103] failed to create some manifests:
Apr 08 18:16:12 ip-10-0-7-174 bootkube.sh[1343]: "0000_05_config-operator_02_registry.cr.yaml": unable to get REST mapping: no matches for kind "Registry" in version "config.openshift.io/v1"
```

**Comment by mfojtik** [comment]
LGTM

**Comment by mfojtik** [comment]
aren't you missing project instance?

**Comment by bparees** [comment]
> removing hold because these are longer part of the payload.

how are they not part of the payload?

**Comment by deads2k** [comment]
> > removing hold because these are longer part of the payload.
> 
> how are they not part of the payload?

They aren't included in the /manifest folder, only in the bootkube manifest

**Comment by abhinavdahiya** [comment]
> > > removing hold because these are longer part of the payload.
> > 
> > 
> > how are they not part of the payload?
> 
> They aren't included in the /manifest folder, only in the bootkube manifest

That would mean that if the user supplied these at install-time, the ones created by this operator are going to race with ones required bu user. cluster-bootstrap doesn't `apply` AFAIK

**Comment by deads2k** [comment]
> That would mean that if the user supplied these at install-time, the ones created by this operator are going to race with ones required bu user. cluster-bootstrap doesn't `apply` AFAIK

I made them render out, so they would modify the rendered ones, not write their own.  I took pains not to overlap with ones created by the installer.

**Comment by abhinavdahiya** [comment]
> I made them render out, so they would modify the rendered ones, not write their own

user's aren't editing on bootstrap node. so your rendered cannot be edited.

**Comment by deads2k** [comment]
> > I made them render out, so they would modify the rendered ones, not write their own
> 
> user's aren't editing on bootstrap node. so your rendered cannot be edited.

this happens during install at the same time the kube-apiserver renders.  If that is untouchable, we have a more fundamental problem.

**Comment by deads2k** [comment]
> > > I made them render out, so they would modify the rendered ones, not write their own
> > 
> > 
> > user's aren't editing on bootstrap node. so your rendered cannot be edited.
> 
> this happens during install at the same time the kube-apiserver renders. If that is untouchable, we have a more fundamental problem.

Either way, at this point it's not any worse.  I may update the CVO later this week with the "create-only" annotation we've kicked around since back in the low level operator resource days last year.

**Comment by deads2k** [comment]
```
E0409 11:45:04.262456    5148 writer.go:119] Marking Degraded due to: machineconfig.machineconfiguration.openshift.io "rendered-master-81f92d5fd54f0aeb14e8494ecb815b36" not found
W0409 11:45:04.422834    5148 daemon.go:292] Booting the MCD errored with machineconfig.machineconfiguration.openshift.io "rendered-master-81f92d5fd54f0aeb14e8494ecb815b36" not found
I0409 11:45:04.422865    5148 run.go:22] Running captured: rpm-ostree status
I0409 11:45:04.481324    5148 daemon.go:738] State: idle
AutomaticUpdates: disabled
Deployments:
* pivot://registry.svc.ci.openshift.org/ci-op-l5v73fr2/stable@sha256:83e25d1681c42be4e9257e288d79d3d3591301e1d5897caff96cecc38d7878f0
              CustomOrigin: Managed by pivot tool
                   Version: 410.8.20190329.0 (2019-03-29T16:35:54Z)

  pivot://docker-registry-default.cloud.registry.upshift.redhat.com/redhat-coreos/ootpa@sha256:84b54f4578bd04aa4e6fae2a7052a3b6df0bf5405dfbba1db44d59d282f3ee2f
              CustomOrigin: Provisioned from oscontainer
                   Version: 410.8.20190325.0 (2019-03-25T18:27:58Z)
I0409 11:45:04.481443    5148 daemon.go:638] In bootstrap mode
E0409 11:45:04.481483    5148 writer.go:119] Marking Degraded due to: machineconfig.machineconfiguration.openshift.io "rendered-master-81f92d5fd54f0aeb14e8494ecb815b36" not found
W0409 11:45:04.586422    5148 daemon.go:292] Booting the MCD errored with machineconfig.machineconfiguration.openshift.io "rendered-master-81f92d5fd54f0aeb14e8494ecb815b36" not found
I0409 11:45:04.586457    5148 run.go:22] Running captured: rpm-ostree status

```

The dreaded mismatch!  Now what....

**Comment by cgwalters** [comment]
Hm, I am confused how this intersects with the MCO.  I see https://github.com/openshift/installer/blob/83ca64d34e7e16935cbaa39fb42a6c8ba9d58c33/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L77

Hm, then the MCO takes `--config-file=/assets/manifests/cluster-config.yaml`...is it something like this PR is causing that config to be different only at bootstrap time?

**Comment by deads2k** [comment]
> Hm, I am confused how this intersects with the MCO. I see https://github.com/openshift/installer/blob/83ca64d34e7e16935cbaa39fb42a6c8ba9d58c33/data/data/bootstrap/files/usr/local/bin/bootkube.sh.template#L77
> 
> Hm, then the MCO takes `--config-file=/assets/manifests/cluster-config.yaml`...is it something like this PR is causing that config to be different only at bootstrap time?

I'm confused too, but I have this pull and https://github.com/openshift/installer/pull/1546 both consistently failing in this mode.

**Comment by deads2k** [comment]
This now only reconciles via the CVO.  It relies on https://github.com/openshift/cluster-version-operator/pull/159

@sttts see if you're happy with validation rules.

**Comment by deads2k** [comment]
/test e2e-aws

kicking since the prereq merged.  
@sttts I'd like to see this merged if you're happy with validation.

**Comment by deads2k** [comment]
@abhinavdahiya looks like the static pod CVO still has the lock, but I have no logs from the bootstrap CVO.  How's that coming?

**Comment by deads2k** [comment]
Gaaaaaaah.  The mcd mismatch is so frustrating. Surely they should be rendering their initial cluster state or *something*.  This is wrapping us around the axle.

This also implies that *something* is treating missing and empty differently.

/retest

Just in case

**Comment by deads2k** [comment]
appears to be https://github.com/openshift/cluster-kube-scheduler-operator/pull/94

**Comment by deads2k** [comment]
And the console is missing logs.

/retest

**Comment by deads2k** [comment]
the master pool worked at least once.

/retest

**Comment by deads2k** [comment]
Looks like it's still having considerable MCD difficulties.  I guess I'll try to split out pieces, merge them and find the one the MCD doesn't like.

**Pull request closed without merging**
