### PR TITLE
Add the status subresource to the image config

### PR DESCRIPTION
**Pull request by dmage**
This should reduce flakes on cluster-image-registry-operator CI.

### CODE REVIEW

**Comment by bparees** [comment]
@deads2k apparently your lgtm didn't approve this. i tagged it manually.

**Comment by dmage** [comment]
```
No rule to make target `test-e2e'.
```

**Comment by bparees** [comment]
if this passes e2e-aws i will be green buttoning it as it's likely a significant source of flakes (no guarantees the registry operator comes up properly right now).

**Comment by bparees** [comment]
@deads2k fyi your branch protection is not setup on this repo.

**Pull request merged**
