### PR TITLE
Fix local image build

### PR DESCRIPTION
**Pull request by tnozicka**
Fixes local image build failure with imagebuilder https://github.com/openshift/imagebuilder/issues/140

/cc @sallyom

### CODE REVIEW

**Comment by sallyom** [comment]
this is a bandaid, but it works - although have to work around [this](https://github.com/openshift/imagebuilder/issues/144), also :woman_shrugging:

**Comment by soltysh** [comment]
> this is a bandaid, but it works - although have to work around [this](https://github.com/openshift/imagebuilder/issues/144), also woman_shrugging

Yeah, I've noticed that, but you can just pull that image and re-try, which is better than not being able to build at all :wink:

**Pull request merged**
