### PR TITLE
Switch to go.mod

### PR DESCRIPTION
**Pull request by damemi**

### CODE REVIEW

**Comment by patrickdillon** [comment]
This bump includes API updates needed for VSphere deployments. Specifically to update `Infra.Status.PlatformStatus.VSphere` I used the release image created by CI to test a vsphere deployment and the cluster infrastructure object is created successfully. 

/lgtm
cc @jcpowermac @sdodson

**Comment by damemi** [comment]
I think these terraform errors are known
/retest

**Comment by patrickdillon** [comment]
/test images
I need these for my personal testing.

**Comment by damemi** [comment]
This was superceded by https://github.com/openshift/cluster-config-operator/pull/113
/close

**Pull request closed without merging**
