### PR TITLE
Bug 2075551: [release-4.9] backport api to commit 019a246c52

### PR DESCRIPTION
**Pull request by candita**
Backport commit 019a246c52 to bump api in release-4.9 for https://bugzilla.redhat.com/show_bug.cgi?id=2075551

### CODE REVIEW

**Review by soltysh — APPROVED** [review]
/lgtm
/approve
/label backport-risk-assessed

**Comment by candita** [comment]
@gangwgr @wangke19 @xingxingxia could one of you please add the `cherry-pick-approved` label to this, it is the same as the backport bump https://github.com/openshift/cluster-config-operator/pull/247

**Comment by candita** [comment]
Ping @gangwgr @wangke19 @xingxingxia could one of you please add the cherry-pick-approved label to this, it is the same as the backport bump #247

**Pull request merged**
